#!/bin/bash
set -euo pipefail

sudo apt install -y bison build-essential curl flex git gnat imagemagick libncurses5-dev m4 nasm python-is-python3 uuid-dev zlib1g-dev libssl-dev pkg-config libcmocka-dev libnss3-dev -y

git clone https://github.com/lingyicute/coreboot.git --depth=1
cd coreboot
git submodule update --init --checkout --recursive

make crossgcc-i386 CPUS=$(nproc)
cp ../coreboot_logo.bmp ./Documentation/
./build-uefi.sh nami
./build-uefi.sh fizz
./build-uefi.sh cave

echo ---------------------------------------------------------------------------------------------------------
echo Build complete
echo ---------------------------------------------------------------------------------------------------------

tree -a ../roms
rm ../roms/*.sha1
sha256sum ../roms/*

echo ---------------------------------------------------------------------------------------------------------
echo "ME_Cleaning 1"
echo ---------------------------------------------------------------------------------------------------------
./util/me_cleaner/me_cleaner.py -c ../roms/*nami*
echo -----------------------
./util/me_cleaner/me_cleaner.py -S -O ../roms/nami-NoME ../roms/*nami*
echo -----------------------
./util/me_cleaner/me_cleaner.py -c ../roms/nami-NoME
echo ---------------------------------------------------------------------------------------------------------
echo 2
echo ---------------------------------------------------------------------------------------------------------
./util/me_cleaner/me_cleaner.py -c ../roms/*fizz*
echo -----------------------
./util/me_cleaner/me_cleaner.py -S -O ../roms/fizz-NoME ../roms/*fizz*
echo -----------------------
./util/me_cleaner/me_cleaner.py -c ../roms/fizz-NoME
echo ---------------------------------------------------------------------------------------------------------
echo 3
echo ---------------------------------------------------------------------------------------------------------
./util/me_cleaner/me_cleaner.py -c ../roms/*cave*
echo -----------------------
./util/me_cleaner/me_cleaner.py -S -O ../roms/cave-NoME ../roms/*cave*
echo -----------------------
./util/me_cleaner/me_cleaner.py -c ../roms/cave-NoME
echo ---------------------------------------------------------------------------------------------------------
echo OK
echo ---------------------------------------------------------------------------------------------------------

sha256sum ../roms/*
